// Service-to-service API of the MRNet auth service. Clients talk to the
// gateway over HTTPS/JSON; everything behind it talks gRPC.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/authv1/internal.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashRequest) Reset() {
	*x = HashRequest{}
	mi := &file_api_authv1_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashRequest) ProtoMessage() {}

func (x *HashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_authv1_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashRequest.ProtoReflect.Descriptor instead.
func (*HashRequest) Descriptor() ([]byte, []int) {
	return file_api_authv1_internal_proto_rawDescGZIP(), []int{0}
}

func (x *HashRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type HashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"` // PHC string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashResponse) Reset() {
	*x = HashResponse{}
	mi := &file_api_authv1_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashResponse) ProtoMessage() {}

func (x *HashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_authv1_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashResponse.ProtoReflect.Descriptor instead.
func (*HashResponse) Descriptor() ([]byte, []int) {
	return file_api_authv1_internal_proto_rawDescGZIP(), []int{1}
}

func (x *HashResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type VerifyRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Password string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	// Empty: verify against a dummy hash so an unknown email costs the same time.
	Hash          string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_api_authv1_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_authv1_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_api_authv1_internal_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *VerifyRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type VerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	NeedsRehash   bool                   `protobuf:"varint,2,opt,name=needs_rehash,json=needsRehash,proto3" json:"needs_rehash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_api_authv1_internal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_authv1_internal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_api_authv1_internal_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *VerifyResponse) GetNeedsRehash() bool {
	if x != nil {
		return x.NeedsRehash
	}
	return false
}

type TakeSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SecretHash    string                 `protobuf:"bytes,3,opt,name=secret_hash,json=secretHash,proto3" json:"secret_hash,omitempty"` // SHA-256 of the presented refresh secret
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TakeSessionRequest) Reset() {
	*x = TakeSessionRequest{}
	mi := &file_api_authv1_internal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeSessionRequest) ProtoMessage() {}

func (x *TakeSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_authv1_internal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeSessionRequest.ProtoReflect.Descriptor instead.
func (*TakeSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_authv1_internal_proto_rawDescGZIP(), []int{4}
}

func (x *TakeSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TakeSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TakeSessionRequest) GetSecretHash() string {
	if x != nil {
		return x.SecretHash
	}
	return ""
}

type TakeSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ok, reused, missing or expired. Only ok carries the session fields.
	Outcome           string `protobuf:"bytes,1,opt,name=outcome,proto3" json:"outcome,omitempty"`
	DeviceId          string `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Scope             string `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	CredentialVersion int64  `protobuf:"varint,4,opt,name=credential_version,json=credentialVersion,proto3" json:"credential_version,omitempty"`
	CreatedAtMs       int64  `protobuf:"varint,5,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"`
	AbsoluteExpMs     int64  `protobuf:"varint,6,opt,name=absolute_exp_ms,json=absoluteExpMs,proto3" json:"absolute_exp_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TakeSessionResponse) Reset() {
	*x = TakeSessionResponse{}
	mi := &file_api_authv1_internal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeSessionResponse) ProtoMessage() {}

func (x *TakeSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_authv1_internal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeSessionResponse.ProtoReflect.Descriptor instead.
func (*TakeSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_authv1_internal_proto_rawDescGZIP(), []int{5}
}

func (x *TakeSessionResponse) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *TakeSessionResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TakeSessionResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *TakeSessionResponse) GetCredentialVersion() int64 {
	if x != nil {
		return x.CredentialVersion
	}
	return 0
}

func (x *TakeSessionResponse) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

func (x *TakeSessionResponse) GetAbsoluteExpMs() int64 {
	if x != nil {
		return x.AbsoluteExpMs
	}
	return 0
}

type GetUserByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailNorm     string                 `protobuf:"bytes,1,opt,name=email_norm,json=emailNorm,proto3" json:"email_norm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByEmailRequest) Reset() {
	*x = GetUserByEmailRequest{}
	mi := &file_api_authv1_internal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByEmailRequest) ProtoMessage() {}

func (x *GetUserByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_authv1_internal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByEmailRequest.ProtoReflect.Descriptor instead.
func (*GetUserByEmailRequest) Descriptor() ([]byte, []int) {
	return file_api_authv1_internal_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserByEmailRequest) GetEmailNorm() string {
	if x != nil {
		return x.EmailNorm
	}
	return ""
}

type User struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserId              string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EmailNorm           string                 `protobuf:"bytes,2,opt,name=email_norm,json=emailNorm,proto3" json:"email_norm,omitempty"`
	PasswordHash        string                 `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	CredentialVersion   int64                  `protobuf:"varint,4,opt,name=credential_version,json=credentialVersion,proto3" json:"credential_version,omitempty"`
	Status              string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	HomeRegion          string                 `protobuf:"bytes,6,opt,name=home_region,json=homeRegion,proto3" json:"home_region,omitempty"`
	DisplayName         string                 `protobuf:"bytes,7,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	PasswordChangedAtMs int64                  `protobuf:"varint,8,opt,name=password_changed_at_ms,json=passwordChangedAtMs,proto3" json:"password_changed_at_ms,omitempty"`
	CreatedAtMs         int64                  `protobuf:"varint,9,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_authv1_internal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_authv1_internal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_authv1_internal_proto_rawDescGZIP(), []int{7}
}

func (x *User) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *User) GetEmailNorm() string {
	if x != nil {
		return x.EmailNorm
	}
	return ""
}

func (x *User) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *User) GetCredentialVersion() int64 {
	if x != nil {
		return x.CredentialVersion
	}
	return 0
}

func (x *User) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *User) GetHomeRegion() string {
	if x != nil {
		return x.HomeRegion
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetPasswordChangedAtMs() int64 {
	if x != nil {
		return x.PasswordChangedAtMs
	}
	return 0
}

func (x *User) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

type ChangePasswordRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CurrentPassword string                 `protobuf:"bytes,2,opt,name=current_password,json=currentPassword,proto3" json:"current_password,omitempty"`
	NewPassword     string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_api_authv1_internal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_authv1_internal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_api_authv1_internal_proto_rawDescGZIP(), []int{8}
}

func (x *ChangePasswordRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChangePasswordRequest) GetCurrentPassword() string {
	if x != nil {
		return x.CurrentPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ChangePasswordResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CredentialVersion int64                  `protobuf:"varint,1,opt,name=credential_version,json=credentialVersion,proto3" json:"credential_version,omitempty"`
	// Sessions created before this time are revoked in every region.
	RevokedBeforeMs int64 `protobuf:"varint,2,opt,name=revoked_before_ms,json=revokedBeforeMs,proto3" json:"revoked_before_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChangePasswordResponse) Reset() {
	*x = ChangePasswordResponse{}
	mi := &file_api_authv1_internal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResponse) ProtoMessage() {}

func (x *ChangePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_authv1_internal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordResponse.ProtoReflect.Descriptor instead.
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return file_api_authv1_internal_proto_rawDescGZIP(), []int{9}
}

func (x *ChangePasswordResponse) GetCredentialVersion() int64 {
	if x != nil {
		return x.CredentialVersion
	}
	return 0
}

func (x *ChangePasswordResponse) GetRevokedBeforeMs() int64 {
	if x != nil {
		return x.RevokedBeforeMs
	}
	return 0
}

var File_api_authv1_internal_proto protoreflect.FileDescriptor

const file_api_authv1_internal_proto_rawDesc = "" +
	"\n" +
	"\x19api/authv1/internal.proto\x12\rmrnet.auth.v1\")\n" +
	"\vHashRequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\"\"\n" +
	"\fHashResponse\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"?\n" +
	"\rVerifyRequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\"C\n" +
	"\x0eVerifyResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12!\n" +
	"\fneeds_rehash\x18\x02 \x01(\bR\vneedsRehash\"m\n" +
	"\x12TakeSessionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vsecret_hash\x18\x03 \x01(\tR\n" +
	"secretHash\"\xdd\x01\n" +
	"\x13TakeSessionResponse\x12\x18\n" +
	"\aoutcome\x18\x01 \x01(\tR\aoutcome\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12-\n" +
	"\x12credential_version\x18\x04 \x01(\x03R\x11credentialVersion\x12\"\n" +
	"\rcreated_at_ms\x18\x05 \x01(\x03R\vcreatedAtMs\x12&\n" +
	"\x0fabsolute_exp_ms\x18\x06 \x01(\x03R\rabsoluteExpMs\"6\n" +
	"\x15GetUserByEmailRequest\x12\x1d\n" +
	"\n" +
	"email_norm\x18\x01 \x01(\tR\temailNorm\"\xc7\x02\n" +
	"\x04User\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"email_norm\x18\x02 \x01(\tR\temailNorm\x12#\n" +
	"\rpassword_hash\x18\x03 \x01(\tR\fpasswordHash\x12-\n" +
	"\x12credential_version\x18\x04 \x01(\x03R\x11credentialVersion\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1f\n" +
	"\vhome_region\x18\x06 \x01(\tR\n" +
	"homeRegion\x12!\n" +
	"\fdisplay_name\x18\a \x01(\tR\vdisplayName\x123\n" +
	"\x16password_changed_at_ms\x18\b \x01(\x03R\x13passwordChangedAtMs\x12\"\n" +
	"\rcreated_at_ms\x18\t \x01(\x03R\vcreatedAtMs\"~\n" +
	"\x15ChangePasswordRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12)\n" +
	"\x10current_password\x18\x02 \x01(\tR\x0fcurrentPassword\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\"s\n" +
	"\x16ChangePasswordResponse\x12-\n" +
	"\x12credential_version\x18\x01 \x01(\x03R\x11credentialVersion\x12*\n" +
	"\x11revoked_before_ms\x18\x02 \x01(\x03R\x0frevokedBeforeMs2\x90\x01\n" +
	"\x06Hasher\x12?\n" +
	"\x04Hash\x12\x1a.mrnet.auth.v1.HashRequest\x1a\x1b.mrnet.auth.v1.HashResponse\x12E\n" +
	"\x06Verify\x12\x1c.mrnet.auth.v1.VerifyRequest\x1a\x1d.mrnet.auth.v1.VerifyResponse2`\n" +
	"\bSessions\x12T\n" +
	"\vTakeSession\x12!.mrnet.auth.v1.TakeSessionRequest\x1a\".mrnet.auth.v1.TakeSessionResponse2\xb6\x01\n" +
	"\bAccounts\x12K\n" +
	"\x0eGetUserByEmail\x12$.mrnet.auth.v1.GetUserByEmailRequest\x1a\x13.mrnet.auth.v1.User\x12]\n" +
	"\x0eChangePassword\x12$.mrnet.auth.v1.ChangePasswordRequest\x1a%.mrnet.auth.v1.ChangePasswordResponseB(Z&mrnet/authentication/api/authv1;authv1b\x06proto3"

var (
	file_api_authv1_internal_proto_rawDescOnce sync.Once
	file_api_authv1_internal_proto_rawDescData []byte
)

func file_api_authv1_internal_proto_rawDescGZIP() []byte {
	file_api_authv1_internal_proto_rawDescOnce.Do(func() {
		file_api_authv1_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_authv1_internal_proto_rawDesc), len(file_api_authv1_internal_proto_rawDesc)))
	})
	return file_api_authv1_internal_proto_rawDescData
}

var file_api_authv1_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_authv1_internal_proto_goTypes = []any{
	(*HashRequest)(nil),            // 0: mrnet.auth.v1.HashRequest
	(*HashResponse)(nil),           // 1: mrnet.auth.v1.HashResponse
	(*VerifyRequest)(nil),          // 2: mrnet.auth.v1.VerifyRequest
	(*VerifyResponse)(nil),         // 3: mrnet.auth.v1.VerifyResponse
	(*TakeSessionRequest)(nil),     // 4: mrnet.auth.v1.TakeSessionRequest
	(*TakeSessionResponse)(nil),    // 5: mrnet.auth.v1.TakeSessionResponse
	(*GetUserByEmailRequest)(nil),  // 6: mrnet.auth.v1.GetUserByEmailRequest
	(*User)(nil),                   // 7: mrnet.auth.v1.User
	(*ChangePasswordRequest)(nil),  // 8: mrnet.auth.v1.ChangePasswordRequest
	(*ChangePasswordResponse)(nil), // 9: mrnet.auth.v1.ChangePasswordResponse
}
var file_api_authv1_internal_proto_depIdxs = []int32{
	0, // 0: mrnet.auth.v1.Hasher.Hash:input_type -> mrnet.auth.v1.HashRequest
	2, // 1: mrnet.auth.v1.Hasher.Verify:input_type -> mrnet.auth.v1.VerifyRequest
	4, // 2: mrnet.auth.v1.Sessions.TakeSession:input_type -> mrnet.auth.v1.TakeSessionRequest
	6, // 3: mrnet.auth.v1.Accounts.GetUserByEmail:input_type -> mrnet.auth.v1.GetUserByEmailRequest
	8, // 4: mrnet.auth.v1.Accounts.ChangePassword:input_type -> mrnet.auth.v1.ChangePasswordRequest
	1, // 5: mrnet.auth.v1.Hasher.Hash:output_type -> mrnet.auth.v1.HashResponse
	3, // 6: mrnet.auth.v1.Hasher.Verify:output_type -> mrnet.auth.v1.VerifyResponse
	5, // 7: mrnet.auth.v1.Sessions.TakeSession:output_type -> mrnet.auth.v1.TakeSessionResponse
	7, // 8: mrnet.auth.v1.Accounts.GetUserByEmail:output_type -> mrnet.auth.v1.User
	9, // 9: mrnet.auth.v1.Accounts.ChangePassword:output_type -> mrnet.auth.v1.ChangePasswordResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_authv1_internal_proto_init() }
func file_api_authv1_internal_proto_init() {
	if File_api_authv1_internal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_authv1_internal_proto_rawDesc), len(file_api_authv1_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_api_authv1_internal_proto_goTypes,
		DependencyIndexes: file_api_authv1_internal_proto_depIdxs,
		MessageInfos:      file_api_authv1_internal_proto_msgTypes,
	}.Build()
	File_api_authv1_internal_proto = out.File
	file_api_authv1_internal_proto_goTypes = nil
	file_api_authv1_internal_proto_depIdxs = nil
}
